export function getGenreEmoji(title: string) {
	const lowerTitle = title.toLowerCase();

	if (lowerTitle.includes('action')) return '💥';
	if (lowerTitle.includes('adult')) return '🔞';
	if (lowerTitle.includes('adventure')) return '🧭';
	if (lowerTitle.includes('beasts')) return '🦁';
	if (lowerTitle.includes('blacksmith')) return '🔨';
	if (lowerTitle.includes('comedy')) return '😂';
	if (lowerTitle.includes('cooking')) return '👨‍🍳';
	if (lowerTitle.includes('crime')) return '🕵️‍♀️';
	if (lowerTitle.includes('dark fantasy')) return '🌑';
	if (lowerTitle.includes('demons')) return '👹';
	if (lowerTitle.includes('drama')) return '🎭';
	if (lowerTitle.includes('ecchi')) return '🍑';
	if (lowerTitle.includes('fantasy')) return '🔮';
	if (lowerTitle.includes('game')) return '🎮';
	if (lowerTitle.includes('gender bender')) return '🔄';
	if (lowerTitle.includes('ghosts')) return '👻';
	if (lowerTitle.includes('gore')) return '🩸';
	if (lowerTitle.includes('harem')) return '💖';
	if (lowerTitle.includes('historical')) return '📜';
	if (lowerTitle.includes('horror')) return '😱';
	if (lowerTitle.includes('isekai')) return '🚪';
	if (lowerTitle.includes('josei')) return '👩';
	if (lowerTitle.includes('magic')) return '✨';
	if (lowerTitle.includes('manga')) return '📖';
	if (lowerTitle.includes('manhwa')) return '📜';
	if (lowerTitle.includes('martial arts')) return '🥋';
	if (lowerTitle.includes('mature')) return '👩‍🦳';
	if (lowerTitle.includes('mecha')) return '🤖';
	if (lowerTitle.includes('medical')) return '🩺';
	if (lowerTitle.includes('military')) return '🎖️';
	if (lowerTitle.includes('monsters')) return '👾';
	if (lowerTitle.includes('music')) return '🎵';
	if (lowerTitle.includes('mystery')) return '🔎';
	if (lowerTitle.includes('one shot')) return '🎯';
	if (lowerTitle.includes('police')) return '🚨';
	if (lowerTitle.includes('psychological')) return '🧠';
	if (lowerTitle.includes('regression')) return '⏪';
	if (lowerTitle.includes('reincarnation')) return '♻️';
	if (lowerTitle.includes('romance')) return '❤️';
	if (lowerTitle.includes('school')) return '🏫';
	if (lowerTitle.includes('sci-fi')) return '👽';
	if (lowerTitle.includes('seinen')) return '👨';
	if (lowerTitle.includes('sexual violence')) return '⛓️';
	if (lowerTitle.includes('shoujo')) return '👧';
	if (lowerTitle.includes('shounen')) return '👦';
	if (lowerTitle.includes('slice of life')) return '☕';
	if (lowerTitle.includes('sport')) return '⚽';
	if (lowerTitle.includes('super power')) return '⚡';
	if (lowerTitle.includes('supernatural')) return '🔮';
	if (lowerTitle.includes('thriller')) return '🔪';
	if (lowerTitle.includes('tragedy')) return '😭';
	if (lowerTitle.includes('vampire')) return '🧛';
	if (lowerTitle.includes('villainess')) return '👑';
	if (lowerTitle.includes('web comic') || lowerTitle.includes('webtoons')) return '📱';
	if (lowerTitle.includes('yuri')) return '👩‍❤️‍💋‍👩';
	return '📚';
}
