export const v3genre: Record<string, string> = {
	Action: 'action',
	Adult: 'adult',
	Adventure: 'adventure',
	Beasts: 'beasts',
	Comedy: 'comedy',
	'Comedy Magic': 'comedy-magic',
	Cooking: 'cooking',
	Crime: 'crime',
	'Dark Fantasy': 'dark-fantasy',
	Demons: 'demons',
	Drama: 'drama',
	Ecchi: 'ecchi',
	Fantasy: 'fantasy',
	Game: 'game',
	'Gender Bender': 'gender-bender',
	Ghosts: 'ghosts',
	Gore: 'gore',
	Harem: 'harem',
	Historical: 'historical',
	Horror: 'horror',
	Isekai: 'isekai',
	Josei: 'josei',
	Magic: 'magic',
	Manga: 'manga',
	Manhwa: 'manhwa',
	'Martial Arts': 'martial-arts',
	Mature: 'mature',
	Mecha: 'mecha',
	Medical: 'medical',
	Military: 'military',
	Monsters: 'monsters',
	Music: 'music',
	Mystery: 'mystery',
	'One Shot': 'one-shot',
	Police: 'police',
	Psychological: 'psychological',
	Reincarnation: 'reincarnation',
	Romance: 'romance',
	School: 'school',
	'School life': 'school-life',
	'Sci-fi': 'sci-fi',
	Seinen: 'seinen',
	'Sexual Violence': 'sexual-violence',
	Shoujo: 'shoujo',
	'Shoujo Ai': 'shoujo-ai',
	Shounen: 'shounen',
	'Shounen Ai': 'shounen-ai',
	'Shounen(B)': 'shounenb',
	'Slice of Life': 'slice-of-life',
	Sport: 'sport',
	Sports: 'sports',
	'Super Power': 'super-power',
	Supernatural: 'supernatural',
	Thriller: 'thriller',
	Tragedy: 'tragedy',
	Villainess: 'villainess',
	'Web Comic': 'web-comic',
	Webtoons: 'webtoons',
	Yuri: 'yuri'
};

export const v3status = ['ongoing', 'end'];

export const v3Type = ['Manga', 'Manhwa', 'Manhua'];

export const v3Order: Record<string, string> = {
	Populer: 'meta_value_num',
	'Baru ditambahkan': 'date',
	'Baru diupdate': 'modified',
	Acak: 'rand'
};
